### ISSUE TITLE
Control Bar has white Play Button

### ISSUE THREAD

**Issue by Krappa420** [williamckha/spicetify-fluent#12] opened 2021-10-05 14:12 UTC
****Describe the bug**
White Play button using Fluent skin

**To Reproduce**
1. Open spotify
2. See the play button is white

**Screenshots**
![image](https://user-images.githubusercontent.com/66475753/136037785-2269eb89-be02-407c-94a2-7fc9c1a42382.png)

**Specifics:**
 - OS: Windows 10 21H1 / 19043.1266
 - Spotify version: 1.1.69.612.gb7409abc
 - Spicetify version: 2.7
 - Theme name: Fluent (Latest Version)

I even cleared backup, redownloaded the theme file, etc. Same issue**

**Comment by Krappa420** [comment] 2021-10-13 04:04
> You need apply extension for fluent Copy Themes/Fluent/fluent.js to Extensions/fluent.js `spicetify config extensions fluent.js` & `spicetify apply`

It's already applied and I did it again as well, same issue

**Comment by CarsonF** [comment] 2021-12-04 23:58
I removed these two patches recommended elsewhere and it works for me now.
```ini
[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,
```

**Comment by alessdangelo** [comment] 2021-12-07 17:14
I have the exact same problem, removing the path didn't do anything and the extension is already applied.

**Comment by rlaphoenix** [comment] 2022-02-21 00:42
Hi, does this still happen? The cause of this issue was never resolved but could have been caused by an outdated colors.ini, or forgetting that you need to copy over the updated extension .js file, not simply update the download within the Themes folder.

**Comment by rlaphoenix** [comment] 2022-02-21 01:59
I was able to reproduce this error:

![image](https://user-images.githubusercontent.com/17136956/154876495-3d9c54d6-b7bb-4c12-b0cf-4c8ec04d3b49.png)

* * *

What can cause it to crash is when `Spicetify.CosmosAsync` is `undefined`, the fluent.js code within `replacePlaylistIcons()` fails and crashes the entire rest of the script execution.

Why `Spicetify.CosmosAsync` can be undefined is not entirely clear, but it seems to usually happen when spicetify-cli hasn't had the chance to add support for a new version. To reproduce this all I did was update to `v1.1.79.763.gc2965cdf`.

**Comment by rlaphoenix** [comment] 2022-02-21 02:01
This would mean this problem is actually an upstream issue, I've made an issue on the spicetify project that when solved, will fix this issue as well:  https://github.com/khanhas/spicetify-cli/issues/1493

Therefore, I'm closing it for now. Anyone who has this issue, simply downgrade your Spotify. Spotify v1.1.78.765 has support with spicetify-cli as of v2.9.0.

**Closed by rlaphoenix** 2022-02-21 02:01 UTC
Labels: question
