### ISSUE TITLE
Play button not displayed properly.

### ISSUE THREAD

**Issue by zcat95** [williamckha/spicetify-fluent#2] opened 2021-08-27 06:38 UTC
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac-a
- Spicetify version: 2.5.0-itsmeow-patch4

## 📝 Provide detailed reproduction steps (if any)

just install theme in powershell as normal

### ✔️ Expected result

The play button should be displayed normally

### ❌ Actual result

The play button is displayed as a round rectangle

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/8362354/131083083-f95154c3-e6ee-4dfa-a34d-9a21ac746d22.png)

**Comment by EpicRive** [comment] 2021-10-01 19:18
Why was this closed? It's clearly an issue that should be fixed. Not having a working pause button in non-English languages is a problem.

**Comment by EpicRive** [comment] 2021-10-01 19:43
By the way, I can confirm this issue persists when using the Russian locale in Spotify. It seems to be a problem only with non-Latin alphabet languages, because changing the language to German doesn't reproduce the problem, while in Russian, Greek and Korean I experience the same issue.

**Comment by williamckha** [comment] 2021-10-01 20:27
This is a known issue, it's because styling for the play/pause buttons is reliant on the English aria-label
Salaron provided a fix but it doesn't seem to work for me, I'll try working a fix tonight

**Closed** 2021-10-02 02:28 UTC
